version: "3"
services:
  mymongo:
    image: "mongo"
    ports:
      - "27017:27017"

  myreader:
    build:
      context: ./GeminiApiApp
    depends_on:
      - mymongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mymongo:27017